services:
  - type: web
    name: traffic-dashboard-backend
    env: python
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd /opt/render/project/backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: DATABASE_URL
        fromDatabase:
          name: traffic_db
          property: connectionString

  - type: static
    name: traffic-dashboard-frontend
    buildCommand: cd frontend && npm install --legacy-peer-deps && npm run build
    staticPublishPath: frontend/build
    routes:
      - path: /api
        destination: http://traffic-dashboard-backend:8000/api
      - path: /ws
        destination: http://traffic-dashboard-backend:8000/ws

databases:
  - name: traffic_db
    plan: free
    ipAllowList: []
